import os, json, re
from bs4 import BeautifulSoup

# Path setup (Linked to th directory structure generated by crawler.py)
BASE_DIR = os.path.abspath(os.path.dirname(__file__))
RAW_DIR = os.path.join(BASE_DIR, "data", "raw")
MANIFEST = os.path.join(RAW_DIR, "manifest.jsonl")

CLEAN_DIR = os.path.join(BASE_DIR, "data", "clean")
PAGES_OUT = os.path.join(CLEAN_DIR, "pages.jsonl")

os.makedirs(CLEAN_DIR, exist_ok=True)

# 1. 정의 Defin NCI-specific boilerplate text
SKIP_SECTION_HEADINGS = {
    "my nci", "moodle", "library", "staff directory", "contact us", 
    "privacy policy", "cookie policy", "terms and conditions", "accessibility",
    "search", "follow us", "quick links"
}

JUNK_LINE_CONTAINS = [
    "student login", "staff login", "apply now", "enquire", 
    "download brochure", "cookie", "privacy", "copyright",
    "staff a-z", "current vacancies", "how to find us", "hire our facilities"
]

# --- Helpers ---

def normalize_ws(s: str) -> str:
    """Sanitize whitespace and newlines"""
    s = re.sub(r"\s+", " ", s or "").strip()
    return s

def get_main_content(html_bytes: bytes):
    """Extract main content from NCI site"""
    soup = BeautifulSoup(html_bytes, "html.parser")
    
    # 1. Scrub design-related code/tags
    for tag in soup(["script", "style", "noscript"]):
        tag.decompose()

    # 2. Locate main content area (NCI typhically uses <main> or specific IDs)
    main = soup.find("main") or soup.find("div", id="main-content") or soup.body
    
    # 3. Remove naviagation and footer
    if main:
        for tag in main.find_all(["nav", "footer", "header", "aside"]):
            tag.decompose()
    
    return main, soup

def extract_title(main, soup_full) -> str:
    """Extract page title (usually the major/course name)"""
    h1 = main.find("h1") if main else None
    if h1:
        return normalize_ws(h1.get_text())
    return normalize_ws(soup_full.title.string) if soup_full.title else "Untitled"

def is_menu_list(text):
    """Determine if content is a 'Menu list' (high newline count, low word density)"""
    lines = text.split('\n')
    if len(lines) > 5: 
        avg_words = sum(len(line.split()) for line in lines) / len(lines)
        if avg_words < 3: # If list has 5+ lins and average < 3 words per line, it's 99% likely a menu.
            return True
    return False

def extract_sections(main):
    sections = []
    if not main: return sections
    
    headings = main.find_all(["h2", "h3"])
    for h in headings:
        heading_text = normalize_ws(h.get_text())
        
        # 1. Filter out meaningless titles
        if heading_text.lower() in SKIP_SECTION_HEADINGS or len(heading_text) < 2:
            continue
            
        texts = []
        for sib in h.find_all_next():
            if sib.name in ["h2", "h3"]: break
            if sib.name in ["p", "li"]:
                txt = normalize_ws(sib.get_text())
                if txt: texts.append(txt)
        
        body = "\n".join(texts).strip()
        
        # 2. Discard if content is a menu list or too short
        if body and not is_menu_list(body) and len(body) > 40:
             sections.append({"heading": heading_text, "text": body})
             
    return sections

def main():
    if not os.path.exists(MANIFEST):
        print(f"Error: {MANIFEST} not found. Run the crawler first.")
        return

    print("Cleaning NCI HTML pages...")
    with open(PAGES_OUT, "w", encoding="utf8") as out:
     
        with open(MANIFEST, "r", encoding="utf8") as f:
            for line in f:
                rec = json.loads(line)
                raw_path = rec.get("raw_path")
                
                if not raw_path or not os.path.exists(raw_path):
                    continue

                with open(raw_path, "rb") as f_html:
                    main_content, soup_full = get_main_content(f_html.read())

                url = rec.get("source_url", "")
                title = extract_title(main_content, soup_full)
                
                # Create data object for NCI
                page_obj = {
                    "doc_id": rec.get("doc_id"),
                    "source_url": url,
                    "title": title,
                    "sections": extract_sections(main_content), # Extract by section
                    "full_text": main_content.get_text("\n", strip=True) if main_content else "",
                    "retrieved_at": rec.get("retrieved_at")
                }

                out.write(json.dumps(page_obj, ensure_ascii=False) + "\n")
    
    print(f"Success! Cleaned data saved to: {PAGES_OUT}")

if __name__ == "__main__":
    main()